djfaceless/cards/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from djfaceless.cards import views

urlpatterns = patterns('djfaceless.cards.views',
    url(r'^$', 'browse', name='browse'),
)

djfaceless/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'djfaceless.views.home', name='home'),
    url(r'^cards/', include('djfaceless.cards.urls', namespace='cards')),

    url(r'^admin/', include(admin.site.urls)),
)

djfaceless/cards/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.template.defaultfilters import slugify

from .managers import CardManager

###################### ENTITIES ########################
# Whenever a new value for one of the entity fields(type, rarity, faction, race) is 
# entered create a record for it for quick filtering purposes

class AbstractEntity(models.Model):
    name = models.CharField(_('name'), max_length=255, unique=True)
    slug = models.SlugField(_('Slug'), max_length=255,
        default=settings.FIELD_PLACEHOLDER, unique=True)

    def __unicode__(self):
        return self.name

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(AbstractEntity, self).save(*args, **kwargs)

class Mechanic(AbstractEntity):
    pass

class Type(AbstractEntity):

    def cards(self):
        return Card.objects.filter(type=self.name)

class Rarity(AbstractEntity):
    TOKEN = 'Token'
    class Meta:
        verbose_name_plural=_('rarities')

    def cards(self):
        return Card.objects.filter(rarity=self.name)

class Race(AbstractEntity):

    def cards(self):
        return Card.objects.filter(race=self.name)

class Faction(AbstractEntity):

    def cards(self):
        return Card.objects.filter(faction=self.name)

class Set(AbstractEntity):

    def cards(self):
        return Card.objects.filter(set=self.name)

######################### CARD ########################

class Card(models.Model):
    game_id = models.CharField(_('game id'), max_length=255, unique=True)
    name = models.CharField(_('name'), max_length=255)
    type = models.ForeignKey(Type, verbose_name=_('type'))
    rarity = models.ForeignKey(Rarity, verbose_name=_('rarity'))

    DRUID, HUNTER, MAGE, PALADIN, PRIEST, ROGUE, SHAMAN, WARLOCK, WARRIOR = (
        'Druid','Hunter','Mage','Paladin',
        'Priest','Rogue','Shaman','Warlock','Warrior'
    )
    PLAYER_CLASS_CHOICES = (
        (DRUID, _(DRUID)),
        (HUNTER,_(HUNTER)),
        (MAGE,_(MAGE)),
        (PALADIN,_(PALADIN)),
        (PRIEST,_(PRIEST)),
        (ROGUE,_(ROGUE)),
        (SHAMAN,_(SHAMAN)),
        (WARLOCK,_(WARLOCK)),
        (WARRIOR,_(WARRIOR)),
    )
    playerClass = models.CharField(_('Class'), max_length=255,
        choices=PLAYER_CLASS_CHOICES, null=True, blank=True)

    cost = models.IntegerField(_('cost'), null=True, blank=True)
    attack = models.IntegerField(_('attack'), null=True, blank=True)
    health = models.IntegerField(_('health'), null=True, blank=True)
    durability = models.IntegerField(_('durability'), null=True, blank=True)

    mechanics = models.ManyToManyField(Mechanic, verbose_name= _('mechanics'),
        null=True)
    text = models.CharField(_('text'), max_length=255,
        null=True, blank=True)
    race = models.ForeignKey(Race, verbose_name=_('race'),
        null=True, blank=True)

    collectible = models.BooleanField(_('collectible'), default=False)

    faction = models.ForeignKey(Faction, verbose_name=_('faction'),
        null=True, blank=True)
    inPlayText = models.CharField(_('in Play Text'), max_length=255,
        null=True, blank=True)
    flavor = models.CharField(_('flavor'), max_length=255,
        null=True, blank=True)
    artist = models.CharField(_('artist'), max_length=255,
        null=True, blank=True)
    elite = models.BooleanField(_('elite'), default=False)

    set = models.ForeignKey(Set, verbose_name=_('set'))
    howToGet = models.CharField(_('how to get'), max_length=255,
        null=True, blank=True)
    howToGetGold = models.CharField(_('how to get golden version'), max_length=255,
        null=True, blank=True)

    search_text = models.TextField(_('Search Text'), blank=True)
    objects = CardManager()

    def __unicode__(self):
        return self.name

    class Meta:
        unique_together = ('game_id','name')
        ordering = ('playerClass','name')

    def save(self, *args, **kwargs):
        self.search_text = "%s %s %s %s %s %s %s"%(
            self.name,
            self.type,
            self.rarity,
            self.get_playerClass_display(),
            self.race,
            self.faction,
            self.text,
            )
        super(Card, self).save(*args, **kwargs)

djfaceless/cards/views.py
from django.shortcuts import render
from djfaceless.cards.models import Card

from django.core.paginator import Paginator

def filter_cards(playerClass='', cost=-1, search_text=''):
    if playerClass or cost>=0:
        query_dict = {}
        if playerClass:
            query_dict['playerClass__exact'] = playerClass
        if cost>=0:
            if cost==7:
                query_dict['cost__gte'] = cost
            else:
                query_dict['cost__exact'] = cost
        query_dict['collectible'] = True
        queryset = Card.objects.filter(**query_dict)
    else:
        queryset = Card.objects.collectible()

    if search_text:
        search_text_in_list = search_text.strip().lower().split(' ')
        print search_text_in_list
        result=[]
        for card in queryset:
            add_card = True
            for string in search_text_in_list:
                if string not in card.search_text.lower():
                    add_card = False
            if add_card:
                result.append(card)
    else:
        result = queryset

    return result


def browse(request):
    card_list = filter_cards(
        playerClass = request.GET.get('playerClass',''),
        cost = int(request.GET.get('cost',-1) or -1),
        search_text = request.GET.get('search_text',''),
    )
    return render(request, 'cards/browse.html', {
        'card_list' : card_list,
        })

djfaceless/cards/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Faceless</title>
</head>
<body>
    <div class="site-header">
        <div class="logo">
            <strong>Faceless</strong>
        </div>
    </div>
    <div class="site-main">
    {% block content %}
        
    {% endblock content %}
    </div>
</body>
</html>

djfaceless/cards/templates/cards/browse.html
{% extends "base.html" %}
{% block content %}
    {% include "cards/card-filter-form.html" %}
    <ul class="card-list">
    {% for card in card_list %}
        <li class="card card--li">
            {{card}}
        </li>
    {% endfor %}
    </ul>

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'cards:browse' %}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'cards:browse' %}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock content %}

djfaceless/cards/templates/cards/card-filter-form.html
<form action="" method='GET'>
    <ul class="form-fields">
        <li>
            <label for="id_playerClass">Class</label>
            <select name="playerClass" id="id_playerClass">
                <option value="">All</option>
                {% for k,v in playerClasses %}
                <option value="{{k}}">{{ v }}</option>
                {% endfor %}
            </select>
        </li>
        <li>
            <label for="id_cost">Cost</label>
            <select name="cost" id="id_cost">
                <option value="">All</option>
                {% for k,v in card_cost_filter_options.items %}
                <option value="{{k}}">{{ v }}</option>
                {% endfor %}
            </select>
        </li>
        <li>
            <label for="id_search_text">Search</label>
            <input class='text-input' type='text' name="search_text" id="id_search_text" placeholer-text='use space to separate multiple search strings'>
        </li>
        <li>
            <input type="submit" class='btn--submit'>
        </li>
    </ul>
</form>